export default {
    hello: 'Hello',
    languageSelector: 'Select Your Language',
    logout: 'Log out',
    invalidLogin: 'Please provide valid login information',
    invalidEmail: 'Please provide a valid email address',
    errInvalidEmail: 'invalid email address',
    email: 'Email address',
    password: 'Password',
    errPassword: 'Please enter a password',
    register: 'Register',
    login: 'Login',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don`t have an account?',
    name: 'First name and last name',
    errName: 'This field should not be empty',
    existentAccount: "Already have an account?",
    home: 'Home',
    profile: 'Profile',
    english: 'English',
    romanian: 'Romanian',
    german: 'German',
    changeLanguage: 'Change language',
    makeAppointment: 'Make appointment',
    appointment: 'Appointments',
    location: 'Location',
    home: 'Home',
    history: "History"
    
  }