export default {
    hello: 'Hello',
    languageSelector: 'Select Your Language',
    logout: 'Log out',
    invalidLogin: 'Please provide valid login information',
    invalidEmail: 'Please provide a valid email address',
    errInvalidEmail: 'invalid email address',
    email: 'Email address',
    password: 'Password',
    errPassword: 'Please enter a password',
    register: 'Register',
    login: 'Login',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don`t have an account?',
    name: 'First name and last name',
    errName: 'This field should not be empty',
    existentAccount: "Already have an account?",
    home: 'Home',
    profile: 'Profile',
    english: 'English',
    romanian: 'Romanian',
    german: 'German',
    changeLanguage: 'Change language',
    makeAppointment: 'Make appointment',
    appointment: 'Appointments',
    appointments: 'Appointments',
    location: 'Location',
    home: 'Home',
    history: "History",
    yourAppointments: "Your appointments",
    youHaveNoAppointments: "You have no appointment",
    nrDaysAppointment: "No. days appointment",
    timeBetweenAppointments: "Time between appointments",
    startingHour: "Starting hour",
    endHour: "End hour",
    infoNrDaysAppointment: "No. of days starting today for which customers can schedule",
    infoTimeBetweenAppointments: "No. of minutes bettween two appointments",
    settings: "Settings",
    save: "Save",
    appointmentDeleted:"Appointment deleted",
    anErrorOccurred:"An error occurred",
    selectDateTitle:"Select date",
    NotificationTitle:"Appointment lives matter!",
    NotificationBody:"You wouldn't want to forget about your appointment, you've been waiting impatiently for tomorrow..",
    AppointmentDone:"Appointment done!"
  }