export default {
    hello: 'Buna',
    languageSelector: 'Alegeti limba de afisaj',
    logout: 'Delogare',
    invalidLogin: 'Introduceti date de autentificare valide',
    invalidEmail: 'Introduceti o adresa e-mail valida',
    errInvalidEmail: 'adresa email invalida',
    email: 'Adresa e-mail',
    password: 'Parola',
    errPassword: 'Introduceti o parola',
    register: 'Inregistrare',
    login: 'Autentificare',
    forgotPassword: 'Ati uitat parola?',
    noAccount: 'Nu aveti un cont inca?',
    name: 'Prenume si nume',
    errName: 'Acest camp nu ar trebui sa fie gol!',
    existentAccount: "Aveti deja un cont?",
    home: 'Acasa',
    profile: 'Profil',
    english: 'Engleză',
    romanian: 'Româna',
    german: 'Germană',
    changeLanguage: 'Schimbă limba',
    makeAppointment: 'Programează',
    appointment: 'Programare',
    appointments: 'Programări',
    location: 'Locație',
    home: 'Acasă',
    history: "Istoric",
    yourAppointments: "Programările tale",
    youHaveNoAppointments: "Nu aveți nicio programare",
    nrDaysAppointment: "Nr. zile programări",
    timeBetweenAppointments: "Timp intre programări",
    startingHour: "Oră deschidere",
    endHour: "Oră inchidere",
    infoNrDaysAppointment: "Nr. de zile incepând de azi pentru care clientii se pot programa",
    infoTimeBetweenAppointments: "Nr. de minute intre doua programări",
    settings: "Setări",
    save: "Salvează",
    appointmentDeleted:"Programarea a fost ștearsă",
    anErrorOccurred:"A intervenit o eroare",
    selectDateTitle:"Selectează dată",
    NotificationTitle:"Viețile programarilor contează!",
    NotificationBody:"Nu uitati de programarea dumneavoastra, ati asteptat cu nerabdare ziua de maine..",
    AppointmentDone:"Programare confirmata!"
  }
