export default {
    hello: 'Buna',
    languageSelector: 'Alegeti limba de afisaj',
    logout: 'Delogare',
    invalidLogin: 'Introduceti date de autentificare valide',
    invalidEmail: 'Introduceti o adresa e-mail valida',
    errInvalidEmail: 'adresa email invalida',
    email: 'Adresa e-mail',
    password: 'Parola',
    errPassword: 'Introduceti o parola',
    register: 'Inregistrare',
    login: 'Autentificare',
    forgotPassword: 'Ati uitat parola?',
    noAccount: 'Nu aveti un cont inca?',
    name: 'Prenume si nume',
    errName: 'Acest camp nu ar trebui sa fie gol!',
    existentAccount: "Aveti deja un cont?",
    home: 'Acasa',
    profile: 'Profil',
    english: 'Engleză',
    romanian: 'Româna',
    german: 'Germană',
    changeLanguage: 'Schimbă limba',
    makeAppointment: 'Programează',
    appointment: 'Programare',
    location: 'Locație',
    home: 'Acasă',
    history: "Istoric"
  }
